### PR TITLE
Markov

### PR DESCRIPTION
**Pull request by applebym**

### CODE REVIEW

**Comment by reshama** [comment]
hi @applebym 
Please keep changes in your forked version.
The master repo is meant to be unchanged.  Thanks.

**Comment by applebym** [comment]
Ah sorry Reshama! Laura and I were going over some GitHub concepts and
mistakenly may have done that. Apologies!

**Comment by applebym** [comment]
Was the master repo changed? We didn't merge any changes.

**Comment by reshama** [comment]
hi @applebym 
No, the master repo was unchanged.
You submitted a pull request with changes which were not accepted.
So, all's well!  :smile:

**Pull request closed without merging**
